@echo off
set POSTGRES_USERNAME=udagram
set POSTGRES_PASSWORD=kezman02
set POSTGRES_HOST=udagram.cm2yg5zbey06.us-east-1.rds.amazonaws.com
set POSTGRES_DB=postgres
set AWS_BUCKET=arn:aws:s3:::udagram-469985309653-dev
set AWS_REGION=us-east-1
set AWS_PROFILE=default
set JWT_SECRET=testing
set URL=http://localhost:8100
